# Generated by Django 5.1.5 on 2025-02-04 14:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0002_book_profile'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='book',
            name='student',
        ),
        migrations.AddField(
            model_name='book',
            name='author',
            field=models.CharField(default=0, max_length=100),
        ),
    ]
