# Generated by Django 5.1.5 on 2025-02-06 13:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0004_book_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='fl',
            field=models.FileField(default=0, upload_to='documents/'),
        ),
    ]
